apiVersion: v1
kind: Service
metadata:
  name: free-ask-bot
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: free-ask-bot
  ports:
    - name: web
      port: 8080
      targetPort: 8080